package desu.nano.wiki;

/**
 * Created by Ker on 19.09.2016.
 */
public enum Action implements Parameter{
    abusefiltercheckmatch("abusefiltercheckmatch"),
    abusefilterchecksyntax("abusefilterchecksyntax"),
    abusefilterevalexpression("abusefilterevalexpression"),
    abusefilterunblockautopromote("abusefilterunblockautopromote"),
    addstudents("addstudents"),
    antispoof("antispoof"),
    block("block"),
    bouncehandler("bouncehandler"),
    categorytree("categorytree"),
    centralauthtoken("centralauthtoken"),
    centralnoticechoicedata("centralnoticechoicedata"),
    centralnoticequerycampaign("centralnoticequerycampaign"),
    changeauthenticationdata("changeauthenticationdata"),
    checktoken("checktoken"),
    cirrusConfigDump("cirrus-config-dump"),
    cirrusMappingDump("cirrus-mapping-dump"),
    cirrusSettingsDump("cirrus-settings-dump"),
    clearhasmsg("clearhasmsg"),
    clientlogin("clientlogin"),
    compare("compare"),
    createaccount("createaccount"),
    cspreport("cspreport"),
    cxconfiguration("cxconfiguration"),
    cxdelete("cxdelete"),
    cxpublish("cxpublish"),
    cxsave("cxsave"),
    xsuggestionlist("cxsuggestionlist"),
    cxtoken("cxtoken"),
    delete("delete"),
    deleteeducation("deleteeducation"),
    deleteglobalaccount("deleteglobalaccount"),
    echomarkread("echomarkread"),
    echomarkseen("echomarkseen"), edit("edit"),
    editmassmessagelist("editmassmessagelist"),
    emailuser("emailuser"), enlist("enlist"),
    expandtemplates("expandtemplates"),
    fancycaptchareload("fancycaptchareload"),
    featuredfeed("featuredfeed"),
    feedcontributions("feedcontributions"),
    feedrecentchanges("feedrecentchanges"),
    feedwatchlist("feedwatchlist"),
    filerevert("filerevert"),
    flagconfig("flagconfig"),
    flow("flow"),
    flowParsoidUtils("flow-parsoid-utils"),
    flowthank("flowthank"),
    globalblock("globalblock"),
    globaluserrights("globaluserrights"),
    graph("graph"),
    help("help"), imagerotate("imagerotate"),
    _import("import"),
    jsonconfig("jsonconfig"),
    languagesearch("languagesearch"),
    linkaccount("linkaccount"),
    liststudents("liststudents"),
    login("login"), logout("logout"),
    managetags("managetags"),
    massmessage("massmessage"),
    mergehistory("mergehistory"),
    mobileview("mobileview"),
    move("move"),
    opensearch("opensearch"),
    options("options"),
    pagetriageaction("pagetriageaction"),
    pagetriagelist("pagetriagelist"),
    pagetriagestats("pagetriagestats"),
    pagetriagetagging("pagetriagetagging"),
    pagetriagetemplate("pagetriagetemplate"),
    paraminfo("paraminfo"),
    parse("parse"),
    parsoidBatch("parsoid-batch"),
    patrol("patrol"),
    protect("protect"),
    purge("purge"),
    query("query"),
    refresheducation("refresheducation"),
    removeauthenticationdata("removeauthenticationdata"),
    resetpassword("resetpassword"),
    review("review"),
    reviewactivity("reviewactivity"),
    revisiondelete("revisiondelete"),
    rollback("rollback"),
    rsd("rsd"),
    sanitizeMapdata("sanitize-mapdata"),
    scribuntoConsole("scribunto-console"),
    setglobalaccountstatus("setglobalaccountstatus"),
    setnotificationtimestamp("setnotificationtimestamp"),
    shortenurl("shortenurl"),
    sitematrix("sitematrix"),
    spamblacklist("spamblacklist"),
    stabilize("stabilize"),
    stashedit("stashedit"),
    strikevote("strikevote"),
    tag("tag"),
    templatedata("templatedata"),
    thank("thank"),
    titleblacklist("titleblacklist"),
    tokens("tokens"),
    transcodereset("transcodereset"),
    ulslocalization("ulslocalization"),
    unblock("unblock"),
    undelete("undelete"),
    unlinkaccount("unlinkaccount"),
    upload("upload"),
    userrights("userrights"),
    visualeditor("visualeditor"),
    visualeditoredit("visualeditoredit"),
    watch("watch"),
    wikilove("wikilove"),
    zeroconfig("zeroconfig");

    private static final String PARAMETER_NAME = "action";
    private String value;

    private Action(String value) {
        this.value = value;
    }

    public String getName() {
        return PARAMETER_NAME;
    }

    public String getValue() {
        return value;
    }
}
